# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Zd1NPDJk5jTUvVnY53-Agg8m2i7FD36
"""

from flask import Flask, render_template, request, flash, redirect, url_for

app = Flask(__name__)
app.secret_key = 'portfolio-secret-key-2024'

# Portfolio data - customize this with your information
portfolio_data = {
    'name': 'k santhosh',
    'title': 'Web Developer & Designer',
    'about': 'I am a passionate full-stack developer with  6 months of experience building web applications. I specialize in Python, Flask, JavaScript, and modern web technologies. I love creating clean, efficient code and solving complex problems.',
    'skills': ['Python', 'Flask', 'HTML/CSS', 'JavaScript', 'SQL', 'Git', 'Bootstrap', 'REST APIs'],
    'projects': [
        {
            'title': 'E-Commerce Website',
            'description': 'A full-featured online store with shopping cart and payment integration',
            'technologies': ['Python', 'Flask', 'SQLite', 'JavaScript']
        },
        {
            'title': 'Task Management App',
            'description': 'A productivity app for managing daily tasks and projects',
            'technologies': ['JavaScript', 'React', 'Node.js', 'MongoDB']
        },
        {
            'title': 'Weather Dashboard',
            'description': 'Real-time weather information with beautiful data visualization',
            'technologies': ['Python', 'API Integration', 'Chart.js', 'Bootstrap']
        }
    ],
    'contact': {
        'email': 'santoshram14333@gmail.com',
        'github': 'https://github.com/santosh380',
        'phone': '9390023059'
    }
}

@app.route('/')
def index():
    return render_template('index.html', data=portfolio_data)

@app.route('/about')
def about():
    return render_template('about.html', data=portfolio_data)

@app.route('/contact', methods=['GET', 'POST'])
def contact():
    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        message = request.form.get('message')

        # Here you would typically save to database or send email
        print(f"New message from {name} ({email}): {message}")

        flash('Thank you for your message! I will get back to you soon.', 'success')
        return redirect(url_for('contact'))

    return render_template('contact.html', data=portfolio_data)

# Error handlers
@app.errorhandler(404)
def not_found(error):
    return render_template('404.html'), 404

if __name__ == '__main__':
    app.run(debug=True)